services:
  private-web:
    build: ./private-web/
    networks:
      private:
        ipv4_address: 172.21.0.3
    ports:
      - "80"
    command: python -m http.server 80
    volumes:
      - ./private-web/contents/:/var/www/html/
  private-host:
    build: ./private-host/
    networks:
      private:
        ipv4_address: 172.21.0.2
      public:
        ipv4_address: 172.21.1.2
    command: nc -lp 31337
    volumes:
      - ./private-host/contents/:/home/user/
  public-host:
    build: ./public-host/
    networks:
      public:
        ipv4_address: 172.21.1.3
    ports:
      - "1336"
      - "1337"
    command: nc -lp 31337
    volumes:
      - ./public-host/contents/:/home/user/
networks:
  private:
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
  public:
    ipam:
      config:
        - subnet: 172.21.1.0/24
          gateway: 172.21.1.1