services:
  web:
    build: ./web/
    networks:
      private:
        ipv4_address: 172.21.0.3
    ports:
      - "80"
    command: python -m http.server 80
    volumes:
      - ./web/contents/:/var/www/html/
  host1:
    build: ./host1/
    networks:
      private:
        ipv4_address: 172.21.0.2
      public:
        ipv4_address: 172.21.1.2
    command: nc -lp 31337
  host2:
    build: ./host2/
    networks:
      public:
        ipv4_address: 172.21.1.3
    command: nc -lp 31337

networks:
  private:
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
  public:
    ipam:
      config:
        - subnet: 172.21.1.0/24
          gateway: 172.21.1.1